# ===============================
# CONFIGURACI�N BASE DE DATOS
# ===============================

spring.application.name=marketpro-backend
server.port=8080

# Configuración de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/marketpro?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect